### ISSUE TITLE
Use int for CandidateCount

### ISSUE THREAD

**Issue by rakyll** [googleapis/go-genai#4]
It's very likely that users will hardcode the candidate count at a call site such as:

```
s.client.Models.GenerateContentStream(
     stream.Context(),
     s.config.Model,
     parts,
     &genai.GenerateContentConfig{CandidateCount: genai.Ptr(int64(5))})
```

In Go, it's more idiomatic to rely on `int` especially when it's clear that you don't need 64-bits. If candidate count was an int, it feels more natural to write without having to cast to `int64`:

```
s.client.Models.GenerateContentStream(
     stream.Context(),
     s.config.Model,
     parts,
     &genai.GenerateContentConfig{CandidateCount: genai.Ptr(5)})
```

**Comment by rakyll** [comment]
We can omit the use of pointers for this field, and make it look like:

```
type GenerateContentConfig struct {
        ...
	CandidateCount int  `json:"candidateCount,omitempty"`
	...
}
```

**Comment by qiaodev** [comment]
I'm on it! Just need to fix some testing magic first.

**Comment by eliben** [comment]
> We can omit the use of pointers for this field, and make it look like:
> 
> ```
> type GenerateContentConfig struct {
>         ...
> 	CandidateCount int  `json:"candidateCount,omitempty"`
> 	...
> }
> ```

What is the meaning of a default value (0) on `CandidateCount`?

**Comment by qiaodev** [comment]
Depends on Backend. GoogleAI throws 400 error but VertexAI return 1 candidate response

**Comment by eliben** [comment]
There should be consistent behavior for the user here, I think. We should be careful to distinguish between "not set" and "explicitly asked 0" -- the latter can result in an error, for example (*). Therefore pointers could definitely be useful here.

(*) An error is always a good start, because it can be removed later and replaced by different behavior. If we start with different behavior, turning it into an error later is impossible if we want to retain backwards compatibility.

**Comment by qiaodev** [comment]
How about using value type for `candidate_count` and overwrite the default 0 to 1? This can ensure the same behavior for the two backends as well as a smooth user journey.

**Comment by qiaodev** [comment]
CandidateCount is now value type. When CandidateCount is zero value, the SDK will overwrite the value to 1
